### DISCUSSION TITLE
Client shows all endpoints offline with orange buble next to them

### DISCUSSION THREAD

**Discussion by mtchetch** [rustdesk/rustdesk#10141] [General]
### Bug Description

In the service desk client all endpoints show as offline (Orange dot next to them). The username and machine name show up so the API access is operational. Client shows Ready with green dot.

The web console shows online status correctly but the client does not.

Running Win 11 and Rustdesk 1.3.3 with the premium version and logged int to the server with the client.
In the network tab Relay server and API server fields are left blank.

### How to Reproduce

The same on all three service desk clients connected to our selfhosted server.

### Expected Behavior

The online status of the machines should be marked with a green dot.

### Operating system(s) on local (controlling) side and remote (controlled) side

Windows 11 -> Windows 10, Windows 11

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.3.3 -> 1.3.3

### Screenshots

![image](https://github.com/user-attachments/assets/446df145-b90b-4b03-b678-da191ef869cb)
![image](https://github.com/user-attachments/assets/b9558c37-f9c5-4eed-8448-f989e223fd2f)

### Additional Context

We are hosting the server with Portainer. Here is the running config:

The ports have been forwarded via an external firewall and since we can connect to endpoints and get username and machine name details I assume that they are correct and working properly.

```


version: '3.9'

networks:
  rustdesk-net:
    external: false

services:
  hbbs:
    container_name: HBBS
    ports:
      - 21114:21114
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server-pro:latest
    command: hbbs
    volumes:
      - /docker/rustdesk:/root
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: on-failure:5

  hbbr:
    container_name: HBBR
    ports:
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server-pro:latest
    command: hbbr
    volumes:
      - /docker/rustdesk:/root
    networks:
      - rustdesk-net
    restart: on-failure:5
```
