### DISCUSSION TITLE
Issue with Linux Mint 22 Wilma - Cinnamon

### DISCUSSION THREAD

**Discussion by damien-s4** [rustdesk/rustdesk#10301] [General]
Hello,

I'm experiencing an issue with RustDesk on Linux Mint 22 Wilma - Cinnamon.

When I launch RustDesk and try to connect to a device by entering its ID, the interface completely freezes. I'm forced to force-quit the program.

I've tested several versions: everything works up to version 1.3.2, but from v1.3.3 onwards, the application becomes unusable.

My operating system is freshly installed, and I've even deleted the .config/rustdesk folder from my home directory (which I usually keep).

Has anyone else encountered this issue?

Thank you.

Sorry if I posted this in the wrong category.

**Comment by rustdesk** [comment]
@fufesou

**Comment by fufesou** [comment]
@damien-s4 Thanks for your feedback. But I cannot reproduce this issue.

![image](https://github.com/user-attachments/assets/7f539d54-ce92-409e-8144-59db78f1011d)

Do you have many recent peers ?

Could you please run close the client and run `rustdesk` in the command line?

Maybe it can print some useful logs.

**Comment by damien-s4** [comment]
Hello,

Thank you for your response.

I tried version 1.3.5 using the command line.
I have some additional information that might be helpful.
The interface freezes when I click in the ID input field.
If I connect to a device that's in my favorites, there's no issue.
But as soon as I click to enter an ID, the interface completely freezes.

Here are the complete logs of the procedure I'm using:

1. Connecting to a favorite
2. Clicking in the ID input field

Try setting transparent
flutter: launch args: []
flutter: initializing FFI main
flutter: _appType:main,info1-id:2d2291fcbe47430ca21a8c7e49b146b7,info2-name:Linux Mint,dir:/home/damien/Documents
flutter: _globalFFI init
flutter: registerEventHandler callback_query_onlines address book peer
flutter: registerEventHandler load_address_book_peers address book peer
flutter: registerEventHandler callback_query_onlines group peer
flutter: registerEventHandler load_group_peers group peer
flutter: registerEventHandler callback_query_onlines recent peer
flutter: registerEventHandler load_recent_peers recent peer
flutter: registerEventHandler callback_query_onlines fav peer
flutter: registerEventHandler load_fav_peers fav peer
flutter: registerEventHandler callback_query_onlines discovered peer
flutter: registerEventHandler load_lan_peers discovered peer
flutter: _globalFFI init end
flutter: registerEventHandler native_ui native_ui
flutter: registerEventHandler check_software_update_finish check_software_update_finish
flutter: restore lpos: 800.0/600.0, offset:718.0/235.0, isMaximized: false, isFullscreen: false
flutter: handled by uni links: false
flutter: [MultiWindowHandler] active window changed: {0}
flutter: launch args: [multi_window, 1, {"type":1,"id":"XXXXXXXXX","password":"","forceRelay":false,"isSharedPassword":false}]
flutter: initializing FFI remote
flutter: _appType:remote,info1-id:2d2291fcbe47430ca21a8c7e49b146b7,info2-name:Linux Mint,dir:/home/damien/Documents
flutter: _globalFFI init
flutter: registerEventHandler callback_query_onlines address book peer
flutter: registerEventHandler load_address_book_peers address book peer
flutter: registerEventHandler callback_query_onlines group peer
flutter: registerEventHandler load_group_peers group peer
flutter: registerEventHandler callback_query_onlines recent peer
flutter: registerEventHandler load_recent_peers recent peer
flutter: registerEventHandler callback_query_onlines fav peer
flutter: registerEventHandler load_fav_peers fav peer
flutter: registerEventHandler callback_query_onlines discovered peer
flutter: registerEventHandler load_lan_peers discovered peer
flutter: _globalFFI init end
flutter: registerEventHandler theme theme
flutter: registerEventHandler language language
flutter: registerEventHandler native_ui native_ui
flutter: [MultiWindowHandler] active window changed: {0, 1}
flutter: registerEventHandler callback_query_onlines address book peer
flutter: registerEventHandler load_address_book_peers address book peer
flutter: registerEventHandler callback_query_onlines group peer
flutter: registerEventHandler load_group_peers group peer
flutter: registerEventHandler callback_query_onlines recent peer
flutter: registerEventHandler load_recent_peers recent peer
flutter: registerEventHandler callback_query_onlines fav peer
flutter: registerEventHandler load_fav_peers fav peer
flutter: registerEventHandler callback_query_onlines discovered peer
flutter: registerEventHandler load_lan_peers discovered peer
flutter: CustomTouchGestureRecognizer init
flutter: onFocusChange(window active:true) true
flutter: restore lpos: 1300.0/740.0, offset:320.0/160.0, isMaximized: true, isFullscreen: false
flutter: restore lpos: 1300.0/740.0, offset:320.0/160.0, isMaximized: true, isFullscreen: false
flutter: create pixelbuffer texture: peerId: 521354206 display:0, textureId:820185104, texturePtr:820185104
flutter: onFocusChange(window active:true) false
flutter: CustomTouchGestureRecognizer init
flutter: onFocusChange(window active:true) true
flutter: onFocusChange(window active:true) false
flutter: [Main] call get_window_info with args  from window 1
flutter: isMaximized true
flutter: EventToUI_Texture display:0, gpuTexture:false
flutter: setTextureType: display=0, isGpuTexture=false
flutter: CustomTouchGestureRecognizer init
flutter: [Main] call get_window_info with args  from window 1
flutter: CustomTouchGestureRecognizer init
flutter: onFocusChange(window active:true) true
flutter: Register custom cursor with key 521354206_65539_320000000_320000000 (0.0,0.0)
flutter: Register custom cursor with key 521354206_65543_320000000_320000000 (16.0,16.0)
flutter: Saving frame: 1: 1920.0/1040.0, offset:1920.0/0.0, isMaximized:true, isFullscreen:false
flutter: [Remote Page] call get_remote_list with args null from window 1

(rustdesk:13408): Gdk-CRITICAL **: 08:37:22.956: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)' failed
flutter: Saving frame: 1: 1920.0/1040.0, offset:1920.0/0.0, isMaximized:true, isFullscreen:false
flutter: [Remote Page] call get_remote_list with args null from window 1
flutter: onFocusChange(window active:true) false

My system:
![systeminfo](https://github.com/user-attachments/assets/56ab5b0b-1fac-436a-8613-01e23339ed10)

**Comment by fufesou** [comment]
Thanks. But I can't see any clues.

Could you please 
1. Test this build? I've removed the auto complete widget.   https://github.com/fufesou/rustdesk/releases/tag/test-10301
2. Run `sudo journalctl -f` to see if there're any clues when clicking the ID input field.

> (rustdesk:13408): Gdk-CRITICAL **: 08:37:22.956: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)' failed

BTW, this line is also printed on my machine.

**Comment by damien-s4** [comment]
No better with this version.
Nothing special in the log.

However, if it helps, I noticed that RustDesk freezes for about 25 seconds when the input ID gains or loses focus.
Then everything returns to normal until the next focus change of the input ID

**Comment by damien-s4** [comment]
FYI, the version compiled with Docker works.
I followed the procedure in the README.md (in the source code), and there were no issues

**Reply by fufesou** [reply]
> I followed the procedure in the README.md (in the source code), and there were no issues

Thanks a lot. I'll try to find the differences.


So, you can compile the flutter app?

Could you please

1. Test this build  https://github.com/fufesou/rustdesk/releases/tag/test-10301 and this build https://github.com/fufesou/rustdesk/releases/tag/test-10301-2
2. try the following code?

<details open><summary>Sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:get/get.dart';
import 'package:auto_size_text/auto_size_text.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class IDTextEditingController extends TextEditingController {
  IDTextEditingController({String? text}) : super(text: text);

  String get id => trimID(value.text);

  set id(String newID) => text = formatID(newID);
}

class IDTextInputFormatter extends TextInputFormatter {
  @override
  TextEditingValue formatEditUpdate(
      TextEditingValue oldValue, TextEditingValue newValue) {
    if (newValue.text.isEmpty) {
      return newValue.copyWith(text: '');
    } else if (newValue.text.compareTo(oldValue.text) == 0) {
      return newValue;
    } else {
      int selectionIndexFromTheRight =
          newValue.text.length - newValue.selection.extentOffset;
      String newID = formatID(newValue.text);
      return TextEditingValue(
        text: newID,
        selection: TextSelection.collapsed(
          offset: newID.length - selectionIndexFromTheRight,
        ),
        // https://github.com/flutter/flutter/issues/78066#issuecomment-797869906
        composing: newValue.composing,
      );
    }
  }
}

String formatID(String id) {
  String id2 = id.replaceAll(' ', '');
  String suffix = '';
  if (id2.endsWith(r'\r') || id2.endsWith(r'/r')) {
    suffix = id2.substring(id2.length - 2, id2.length);
    id2 = id2.substring(0, id2.length - 2);
  }
  if (int.tryParse(id2) == null) return id;
  String newID = '';
  if (id2.length <= 3) {
    newID = id2;
  } else {
    var n = id2.length;
    var a = n % 3 != 0 ? n % 3 : 3;
    newID = id2.substring(0, a);
    for (var i = a; i < n; i += 3) {
      newID += " ${id2.substring(i, i + 3)}";
    }
  }
  return newID + suffix;
}

String trimID(String id) {
  return id.replaceAll(' ', '');
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final RxBool _idInputFocused = false.obs;
  final _idController = IDTextEditingController();

  Widget getConnectionPageTitle(BuildContext context, bool isWeb) {
  return Row(
    children: [
      Expanded(
          child: Row(
        children: [
          AutoSizeText(
            'Control Remote Desktop',
            maxLines: 1,
            style: Theme.of(context)
                .textTheme
                .titleLarge
                ?.merge(TextStyle(height: 1)),
          ).marginOnly(right: 4),
          Tooltip(
            waitDuration: Duration(milliseconds: 300),
            message: "id_input_tip",
            child: Icon(
              Icons.help_outline_outlined,
              size: 16,
              color: Theme.of(context)
                  .textTheme
                  .titleLarge
                  ?.color
                  ?.withOpacity(0.5),
            ),
          ),
        ],
      )),
    ],
  );
}

  Widget _buildRemoteIDTextField(BuildContext context) {
    var w = Container(
      width: 320 + 20 * 2,
      padding: const EdgeInsets.fromLTRB(20, 24, 20, 22),
      decoration: BoxDecoration(
          borderRadius: const BorderRadius.all(Radius.circular(13)),
          border: Border.all(color: Theme.of(context).colorScheme.background)),
      child: Ink(
        child: Column(
          children: [
            getConnectionPageTitle(context, false).marginOnly(bottom: 15),
            Row(
              children: [
                Expanded(
                    child: TextField(
                  autocorrect: false,
                  enableSuggestions: false,
                  keyboardType: TextInputType.visiblePassword,
                  style: const TextStyle(
                    fontFamily: 'WorkSans',
                    fontSize: 22,
                    height: 1.4,
                  ),
                  maxLines: 1,
                  cursorColor: Theme.of(context).textTheme.titleLarge?.color,
                  decoration: InputDecoration(
                      filled: false,
                      counterText: '',
                      hintText: _idInputFocused.value
                          ? null
                          : 'Enter Remote ID',
                      contentPadding: const EdgeInsets.symmetric(
                          horizontal: 15, vertical: 13)),
                  inputFormatters: [IDTextInputFormatter()],
                  onChanged: (v) {
                    _idController.id = v;
                  },
                  onSubmitted: (_) {
                    print('onSubmitted');
                  },
                )),
              ],
            ),
            Padding(
              padding: const EdgeInsets.only(top: 13.0),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  const SizedBox(
                    width: 17,
                  ),
                ],
              ),
            )
          ],
        ),
      ),
    );
    return Container(
        constraints: const BoxConstraints(maxWidth: 600), child: w);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: _buildRemoteIDTextField(context),
      ),
    );
  }
}

```

</details>

**Reply by fufesou** [reply]
The docker build version is not flutter app, so it's ok.

I'll compile the simple flutter demo, then please test it.

**Comment by damien-s4** [comment]
https://github.com/fufesou/rustdesk/releases/tag/test-10301 : same focus issue

https://github.com/fufesou/rustdesk/releases/tag/test-10301-2 : The application starts but no window appears and in the log, only "Try setting transparent"

I compiled your example and the results are interesting.
When I launch the application in debug from Visual Code, everything works perfectly.
However, when I launch it from a terminal, I observe the same blocking issue

**Reply by fufesou** [reply]
> However, when I launch it from a terminal, I observe the same blocking issue

Thanks a lot. I think we can find the issue from this point.

Could you please try the following code, it uses less third pubs.

What's the flutter version did you use, could you please also try `flutter 3.19.6`?

<details open><summary>main.dart</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Widget getConnectionPageTitle(BuildContext context, bool isWeb) {
    return Row(
      children: [
        Expanded(
            child: Row(
          children: [
            Text(
              'Control Remote Desktop',
              maxLines: 1,
              style: Theme.of(context)
                  .textTheme
                  .titleLarge
                  ?.merge(TextStyle(height: 1)),
            ),
            Tooltip(
              waitDuration: Duration(milliseconds: 300),
              message: "id_input_tip",
              child: Icon(
                Icons.help_outline_outlined,
                size: 16,
                color: Theme.of(context)
                    .textTheme
                    .titleLarge
                    ?.color
                    ?.withOpacity(0.5),
              ),
            ),
          ],
        )),
      ],
    );
  }

  Widget _buildRemoteIDTextField(BuildContext context) {
    var w = Container(
      width: 320 + 20 * 2,
      padding: const EdgeInsets.fromLTRB(20, 24, 20, 22),
      decoration: BoxDecoration(
          borderRadius: const BorderRadius.all(Radius.circular(13)),
          border: Border.all(color: Theme.of(context).colorScheme.background)),
      child: Ink(
        child: Column(
          children: [
            getConnectionPageTitle(context, false),
            Row(
              children: [
                Expanded(
                    child: TextField(
                  autocorrect: false,
                  enableSuggestions: false,
                  keyboardType: TextInputType.visiblePassword,
                  style: const TextStyle(
                    fontFamily: 'WorkSans',
                    fontSize: 22,
                    height: 1.4,
                  ),
                  maxLines: 1,
                  cursorColor: Theme.of(context).textTheme.titleLarge?.color,
                  decoration: InputDecoration(
                      filled: false,
                      counterText: '',
                      hintText: 'Enter Remote ID',
                      contentPadding: const EdgeInsets.symmetric(
                          horizontal: 15, vertical: 13)),
                  onChanged: (v) {
                    print('onChanged');
                  },
                  onSubmitted: (_) {
                    print('onSubmitted');
                  },
                )),
              ],
            ),
          ],
        ),
      ),
    );
    return Container(
        constraints: const BoxConstraints(maxWidth: 600), child: w);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: _buildRemoteIDTextField(context),
      ),
    );
  }
}


```

</details>


<details open><summary>pub.yaml</summary>

```yaml

name: simple_test
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package


```

</details>
