### DISCUSSION TITLE
How do I use my Rust Desk server to connect to other computers not configured with my own Rust Desk server?

### DISCUSSION THREAD

**Discussion by YamiYukiSenpai** [rustdesk/rustdesk#12017] [Q&A]
I was trying to help a friend earlier and when I asked him to install Rust Desk, I was unable to connect.

I had to remove my relay and ID server in the config, and use the public servers, in order to connect.

Is there a way to do this without needing to either give them my server name and key or removing my own config?

My server is setup with Docker

```
services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r <public domain URL>:21117
    volumes:
      - ./data:/root
#    network_mode: "host"
    networks:
      - nginx-proxy_frontend
## using Nginx proxy's stream
#    ports: ## using Nginx proxy's stream
#      - 21115:21115
#      - 21116:21116
#      - 21116:21116/udp
#      - 21118:21118
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
#    network_mode: "host"
    networks:
      - nginx-proxy_frontend
## using Nginx proxy's stream
#    ports: 
#      - 21117:21117
#      - 21119:21119
    restart: unless-stopped

networks:
  nginx-proxy_frontend:
    external: true
```
```
services:
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
      - '8080:81'
      ## Stream ports - RustDesk
      - '21115:21115'
      - '21116:21116'
      - '21116:21116/udp'
      - '21117:21117'
      - '21118:21118'
      - '21119:21119'
```

I've also confirmed that I can connect to my own computers from an external network with the relay and ID servers setup.
