### DISCUSSION TITLE
How can I be sure encryption is enabled? (Docker)

### DISCUSSION THREAD

**Discussion by mcdaniels2k12** [rustdesk/rustdesk#2568] [Q&A]
Hi folks,
just started using docker (portainer-stack-install) of Rustdesk.

the compose-file I used:

```
version: '3'

networks:
  rustdesk-net:
    external: false

services:
  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r my.domain.com:21117 -k _
    volumes:
      - ./hbbs:/root
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server:latest
    command: hbbr -k _
    volumes:
      - ./hbbs:/root
    networks:
      - rustdesk-net
    restart: unless-stopped

```
Btw. I intentionally set both volumes (of hbbr and hbbs) to the same folder, as the files in there need to be the same.

So far it seems to work. If I do not supply the public-key, connections are refused. Only if I supply the public-key in the rustdesk-clients connections are established.

**Does that automatically mean, that my connections are encrypted and unencrypted connections are impossible?**

So can I rely on that, or is there a way to check wheter connections are encrypted or not?
