### DISCUSSION TITLE
Workflow separation

### DISCUSSION THREAD

**Discussion by Orholt** [rustdesk/rustdesk#3418] [General]
Hi, I have an Idea that you could create separate workflows from big "Full Flutter CI".

Why?
At this moment this one massive workflow takes +- 1.5h to finish, it is a big waste of time.

If you separate it workflows to something like:
- Generate Bridge
- Build VCPKG Deps
- Flutter build MacOS
- Flutter build Windows
- Flutter build Android (arm64)
- Flutter build Linux

It will be much easier to test everything, for example I'm right now working on Autostart Feature and I need to build only Android version in order to test if I didn't break anything. And separate workflow works like charm from me, from waiting 1.5h I managed to achieve only ~ 15 minutes.

Also you could clean up your's Full Flutter CI workflow file by just reusing existing runs by using keyword `uses` for example in one of my repos It look's like this:
```yaml
jobs:

  Tests:
    uses: ./.github/workflows/test-api.yml
  
  build_and_push:
    name: Build and Push
    needs: [Tests]
    env:
        BUILD_CONFIG: Release
        SOLUTION: Project.sln
    runs-on: ubuntu-latest
    steps:
    .... etc
```
