### DISCUSSION TITLE
Does the nightly build work for anyone in MacOS?

### DISCUSSION THREAD

**Discussion by jacotec** [rustdesk/rustdesk#3683] [General]
Hi,

I'm just wondering if the nightly build works for you on MacOS? I simply can't get the GUI opened in the nightly. The only one which works is the 1.19 release (which has a dark icon on a dark menu bar background).

I'd like to compile my own version bound to my server for remote support.

**Comment by kecher** [comment]
@jacotec Same thing happening to me here.. It compiles via Github actions, but it doesn't seem to run at all on my Mac, and Apple notarization service reports the package is invalid?

**Reply by rustdesk** [reply]
> Apple notarization

@Kingtous can you confirm?

**Reply by Kingtous** [reply]
> @jacotec Same thing happening to me here.. It compiles via Github actions, but it doesn't seem to run at all on my Mac, and Apple notarization service reports the package is invalid?

Please use the dmg compiled by our official repo, if u compile rustdesk by yourself, this problem happens. I can confirm the nightly build in our official repo works well.

**Reply by kecher** [reply]
This doesn't really address the use case that @jacotec and I have. In order for us to use our self-hosted instances with our customers, we need to provide them with prebuilt client binaries with our server addresses and keys hardcoded in per your instructions here https://rustdesk.com/docs/en/self-host/hardcode-settings/

Please advise if there is any solution, and when do you expect the source will be compile-able by external users?

**Reply by jacotec** [reply]
@Kingtous Fully agree to @kecher. I can't send something out and then add a document and ask for more configuration. It should work with a github actions build with server address and key in the secrets.

**Reply by kecher** [reply]
@jacotec Apparently when the build crashes on my Mac, it reports a missing Flutter library (or is it a code signing issue?).  I did try to deep sign and then notarize the app with my Apple Developer account, but it doesn't seem to do the trick..

Does that happen to you too? (Excerpt from log below)

`Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '@rpath/FlutterMacOS.framework/Versions/A/FlutterMacOS'
Referenced from: '/Applications/RustDesk.app/Contents/MacOS/RustDesk'
Reason: tried: '' (no such file), '' (no such file), '' (code signature in <4C4C440A-5555-3144-A13C-FF290DB87CC0> '' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '' (no such file), '' (no such file), '
(terminated at launch; ignore backtrace)`

**Reply by daedalusal** [reply]
did you find a fix for this problem, as i am encoutering the same problem

**Comment by dissidius** [comment]
any news on this ??

**Comment by dissidius** [comment]
You need to build from source in a mac system as i have tested and it works, i've made a guide which i'm sharing in attachment if missing smth or forgot smth, plz add (got it from terminal's history)
[macOS Client.txt](https://github.com/rustdesk/rustdesk/files/11574012/macOS.Client.txt)

**Comment by dissidius** [comment]
Anyway if installing the service on boot, tested in all macOS Ventura Builds including 13.4 after closing the app and trying to reopen, it doesn't open anymore
Also after Reboot where the service is Already started, it Crashes if trying to open
If i unload the service/exit service daemon
It Works again
Here are the logs
[RustDesk.zip](https://github.com/rustdesk/rustdesk/files/11574047/RustDesk.zip)

**Comment by stfast** [comment]
It does work on Mac Intel (x86_64), but not on Apple Silicon:

Here is an error from Apple Silicon M1:

 $ /Applications/RustDesk.app/Contents/MacOS/RustDesk 
dyld[51951]: Library not loaded: @rpath/FlutterMacOS.framework/Versions/A/FlutterMacOS
  Referenced from: <A46A7EEB-C568-318B-ADE2-E510975894CB> /Applications/RustDesk.app/Contents/MacOS/RustDesk
  Reason: tried: '/usr/lib/swift/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file), '/usr/lib/swift/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file), '/Applications/RustDesk.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' (code signature in <4C4C4477-5555-3144-A1BE-C45F17E9DB64> '/Applications/RustDesk.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Applications/RustDesk.app/Contents/MacOS/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file), '/Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file), '/Applications/RustDesk.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' (code signature in <4C4C4477-5555-3144-A1BE-C45F17E9DB64> '/Applications/RustDesk.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/usr/lib/swift/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file), '/usr/lib/swift/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file), '/Applications/RustDesk.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' (code signature in <4C4C4477-5555-3144-A1BE-C45F17E9DB64> '/Applications/RustDesk.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Applications/RustDesk.app/Contents/MacOS/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file), '/Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file), '/Applications/RustDesk.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' (code signature in <4C4C4477-5555-3144-A1BE-C45F17E9DB64> '/Applications/RustDesk.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Library/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file), '/System/Library/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file, not in dyld cache)
zsh: abort      /Applications/RustDesk.app/Contents/MacOS/RustDesk

**Comment by fufesou** [comment]
> You can run x86 on M1 after turning on Rosetta, https://support.apple.com/en-sg/HT211861

https://github.com/rustdesk/rustdesk/issues/6335#issuecomment-1826297606

**Comment by angela-d** [comment]
The cause is in the error:

>  '' (code signature in <4C4C440A-5555-3144-A13C-FF290DB87CC0> '' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?))

These build instructions: https://rustdesk.com/docs/en/dev/build/all/

Are not complete.
In defense of the developers they probably don't want to support custom builds, particularly if they sell licenses or pro plans.

However, for anyone who's in an industry with regulations, you can't really use Rust Desk as-is - so it makes even trialing the software a bit difficult if it can't tick all of the boxes (such as working with MDM out of the box / no third-party rendezvous).

Fixing the problem, you either:

- Need an MDM that can sign software for you, or
- Take a look at the build config and fix what's missing

Build config: https://github.com/rustdesk/rustdesk/blob/master/.github/workflows/flutter-build.yml
Note variables like `secrets.MACOS_P12_BASE64` , `secrets.MACOS_P12_PASSWORD` , `secrets.MACOS_NOTARIZE_JSON` and so on
(basically anything prefixed with **secrets.**) -- these should be under your project repo’s Settings > Secrets and Variables > Actions,
too (Rust Desk's build instructions only tell you to put **two** variables here.)

With only those two, you'll get a successful build, but your app won't work and you'll get the error referenced above.


Some examples:

- If you don't need notarization or code signing, remove:


```yaml
      - name: Import notarize key
        if: env.MACOS_P12_BASE64 != null
        uses: timheuer/base64-to-file@v1.2
        with:
          # https://gregoryszorc.com/docs/apple-codesign/stable/apple_codesign_rcodesign.html#notarizing-and-stapling
          fileName: rustdesk.json
          fileDir: ${{ github.workspace }}
          encodedString: ${{ secrets.MACOS_NOTARIZE_JSON }}
```


and


```yaml
          # notarize the rustdesk-${{ env.VERSION }}.dmg
          rcodesign notary-submit --api-key-path ${{ github.workspace }}/rustdesk.json  --staple rustdesk-${{ env.VERSION }}.dmg
```

and

```yaml
      - name: Import the codesign cert
        if: env.MACOS_P12_BASE64 != null
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.MACOS_P12_BASE64 }}
          p12-password: ${{ secrets.MACOS_P12_PASSWORD }}
          keychain: rustdesk

      - name: Check sign and import sign key
        if: env.MACOS_P12_BASE64 != null
        run: |
          security default-keychain -s rustdesk.keychain
          security find-identity -v
```

and 

```yaml
      - name: Install rcodesign tool
        if: env.MACOS_P12_BASE64 != null
        shell: bash
        run: |
          pushd /tmp
          wget https://github.com/indygreg/apple-platform-rs/releases/download/apple-codesign%2F0.22.0/apple-codesign-0.22.0-macos-universal.tar.gz
          tar -zxvf apple-codesign-0.22.0-macos-universal.tar.gz
          mv apple-codesign-0.22.0-macos-universal/rcodesign /usr/local/bin
          popd
```

Refactor the following, FROM:

```yaml
      - name: Codesign app and create signed dmg
        if: env.MACOS_P12_BASE64 != null && env.UPLOAD_ARTIFACT == 'true'
        run: |
          # Patch create-dmg to give more attempts to unmount image
          CREATE_DMG="$(command -v create-dmg)"
          CREATE_DMG="$(readlink -f "$CREATE_DMG")"
          sed -i -e 's/MAXIMUM_UNMOUNTING_ATTEMPTS=3/MAXIMUM_UNMOUNTING_ATTEMPTS=7/' "$CREATE_DMG"
          # Unlock keychain
          security default-keychain -s rustdesk.keychain
          security unlock-keychain -p ${{ secrets.MACOS_P12_PASSWORD }} rustdesk.keychain
          # start sign the rustdesk.app and dmg
          rm rustdesk-${{ env.VERSION }}.dmg || true
          codesign --force --options runtime -s ${{ secrets.MACOS_CODESIGN_IDENTITY }} --deep --strict ./flutter/build/macos/Build/Products/Release/RustDesk.app -vvv
          create-dmg --icon "RustDesk.app" 200 190 --hide-extension "RustDesk.app" --window-size 800 400 --app-drop-link 600 185 rustdesk-${{ env.VERSION }}.dmg ./flutter/build/macos/Build/Products/Release/RustDesk.app
          codesign --force --options runtime -s ${{ secrets.MACOS_CODESIGN_IDENTITY }} --deep --strict rustdesk-${{ env.VERSION }}.dmg -vvv
          # notarize the rustdesk-${{ env.VERSION }}.dmg
          rcodesign notary-submit --api-key-path ${{ github.workspace }}/rustdesk.json  --staple rustdesk-${{ env.VERSION }}.dmg

```

to something like:

```yaml
      - name: Create signed dmg
        if: env.UPLOAD_ARTIFACT == 'true'
        run: |
          # Patch create-dmg to give more attempts to unmount image
          CREATE_DMG="$(command -v create-dmg)"
          CREATE_DMG="$(readlink -f "$CREATE_DMG")"
          sed -i -e 's/MAXIMUM_UNMOUNTING_ATTEMPTS=3/MAXIMUM_UNMOUNTING_ATTEMPTS=7/' "$CREATE_DMG"

          # start sign the rustdesk.app and dmg
          rm rustdesk-${{ env.VERSION }}.dmg || true
          create-dmg --icon "RustDesk.app" 200 190 --hide-extension "RustDesk.app" --window-size 800 400 --app-drop-link 600 185 rustdesk-${{ env.VERSION }}.dmg ./flutter/build/macos/Build/Products/Release/RustDesk.app
```

(not tested)

If you do not have an MDM that signs your apps, you will need an Apple Developer account.

This blog offers a nice overview of how to set this up (once you have an Apple Developer account): https://federicoterzi.com/blog/automatic-code-signing-and-notarization-for-macos-apps-using-github-actions/

- If you follow this tutorial, do not use his example vars, instead, go through [Rust Desk's build config](https://github.com/rustdesk/rustdesk/blob/master/.github/workflows/flutter-build.yml) and search for everything prefixed with **secrets.** - the suffix of those types of variables are what you need saved in your Github Actions, alongside your rendezvous server and key.

If you do not have an Apple Developer account, check here: https://developer.apple.com/support/membership-fee-waiver/
>  if you operate an ... nonprofit organization, accredited educational institution, or government entity, select the option to request a fee waiver when completing your enrollment

Unsure if free accounts are still offered, but worth a shot if your organization doesn't follow under any of the fee waiver orgs: https://developer.4d.com/4d-for-ios/docs/en/free-developer-account.html
