### DISCUSSION TITLE
Cannot Add flutter_rust_bridge Dependency from Git Repository

### DISCUSSION THREAD

**Discussion by btc2100k** [rustdesk/rustdesk#4536] [Q&A] [answered]
Hello,

I am trying to build the nightly latest RustDesk (commit [52ce3dd2](https://github.com/rustdesk/rustdesk/commit/52ce3dd2c299e262a54af0b5350fa60f66215e60))

I am receiving this error repeatedly on the 'flutter_rust_bridge' dependency.

```toml
flutter_rust_bridge = { git = "https://github.com/SoLongAndThanksForAllThePizza/flutter_rust_bridge", optional = true }
```

I have also specified it for certain targets as:

```toml
[target.'cfg(any(target_os = "android", target_os = "ios"))'.dependencies]
flutter_rust_bridge = { git = "https://github.com/SoLongAndThanksForAllThePizza/flutter_rust_bridge" }
```

and as a build dependency:

```toml
[build-dependencies]
flutter_rust_bridge_codegen = { git = "https://github.com/SoLongAndThanksForAllThePizza/flutter_rust_bridge" }
```

However, I'm consistently receiving the following error when running `cargo update`:

```
error: no matching package named `flutter_rust_bridge` found
location searched: https://github.com/SoLongAndThanksForAllThePizza/flutter_rust_bridge
required by package `rustdesk v1.2.0 (C:\Users\admin\rustdesk)`
```

I have tried several approaches to resolve this issue:

- I checked the repository's `Cargo.toml` file and verified that the package name is indeed `flutter_rust_bridge`.
- I confirmed that the repository is public and contains a `Cargo.toml` file at its root.
- I tried specifying the `branch = "master"` in the git dependency in my `Cargo.toml`, but the error persisted.
- I verified that the latest commit on the master branch of the `flutter_rust_bridge` repository is newer than the `Cargo.lock` file in my project.

Unfortunately, none of these attempts have resolved the issue. I would appreciate any help or guidance to resolve this issue. Thank you in advance for your support.
