### DISCUSSION TITLE
Unable to connect to remote desktop through self-built relay server, prompt ID does not exist

### DISCUSSION THREAD

**Discussion by dong50252409** [rustdesk/rustdesk#5657] [Q&A]
I built a relay server in Debian according to https://rustdesk.com/docs/en/self-host/rustdesk-server-oss/docker/, but after the client is configured, it cannot connect to the remote desktop. The prompt ID does not exist. 

```
version: '3'

networks:
  rustdesk-net:
    external: false

services:
  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r xxxxx.com:21117
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    restart: unless-stopped
```

![QQ图片20230911160413](https://github.com/rustdesk/rustdesk/assets/17381957/84411122-df4b-41e8-9e64-78ee637a0b9c)
![QQ图片20230911160456](https://github.com/rustdesk/rustdesk/assets/17381957/0c8a2bc5-604c-4767-bf52-5b67bbba323e)
