### DISCUSSION TITLE
For those who want to self host, I have a modified docker compose that will make it easy.

### DISCUSSION THREAD

**Discussion by grahamIT** [rustdesk/rustdesk#5924] [Show and tell]
I started with the one on in the docs and modified it to not share host networking:

```
version: '3'

services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    volumes:
      - ./data:/root
    ports:
      - "21115:21115"
      - "21116:21116"
      - "21116:21116/udp"
      - "21118:21118"
    depends_on:
      - hbbr
    restart: unless-stopped


  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    ports:
      - "21117:21117"
      - "21119:21119"
    restart: unless-stopped
```

I created this in order to self host as the main service is having issues
