### DISCUSSION TITLE
no secure connection supported for web client?

### DISCUSSION THREAD

**Discussion by liyimeng** [rustdesk/rustdesk#6023] [General]
### Bug Description

I deploy a self-host relay server, and serve the web client  on a https server. Nobody should use http nowadays, right :)

when loading the web client, it dose not work in chrome for Firefox  because the browser reject to send insecure connection to port 21118, see attach picture

### How to Reproduce

- deploy relay server
- deploy web client on an https server
- open the web client in chrome or Firefox

### Expected Behavior

Relay server should support both https and http on port 21118. 

### Operating system(s) on local side and remote side

web ---> linux 

### RustDesk Version(s) on local side and remote side

web --> 1.2.3

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/3155688/e3f37879-e139-4898-b7df-3d3166ff8ec1)

**Comment by TBG-FR** [comment]
I think that's why the "public" web client is in HTTP (w\ HSTS) and not HTTPS https://github.com/rustdesk/rustdesk/issues/856

Got the same issue here, how did you solve it ?

**Reply by TBG-FR** [reply]
I'm not sure about it, but it looks like RustDesk remote control/connection works without a valid WSS url  (I get WebSocket errors on their public web client http://45.76.181.120:8080/#/ and on my local deployment http://localhost:5000/#/ and I still manage to connect myself to a RustDesk Desktop Client), so maybe we could "ignore" that setting/check... (looks like you can also disable that check in your browser, but that won't work for other users)

**Reply by TBG-FR** [reply]
I managed to modify the web client to use `wss://` instead of `ws://` so now the page is loading, in https, without errors... but the errors happens at connection time, so I guess now the issue is on server side

**Reply by TBG-FR** [reply]
https://github.com/rustdesk/rustdesk/discussions/5145#discussioncomment-8346782

**Reply by TBG-FR** [reply]
I finally did it 🥳 Here's the setup, using *Traefik*
1. Rebuild **RustDesk Web Client** and edit `flutter/web/js/src/connection.ts` to force WebSocket Secure protocol
```diff
let HOST = localStorage.getItem("rendezvous-server") || HOSTS[0];
-const SCHEMA = "ws://";
+const SCHEMA = "wss://";
```
3. Expose your RustDesk Web Client in HTTPS using Traefik
```yaml
  # #####
  # # RustDesk Web Client
  # #####
  client:
    container_name: rustdesk-web-client
    image: your_custom_rebuilt_image:tag
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rustdesk-web-client.rule=Host(`rustdesk.yourdomain.com`)"
      - "traefik.http.services.rustdesk-web-client.loadbalancer.server.port=5000"
      # HTTP to HTTPS redirection
      - "traefik.http.routers.rustdesk-web-client.entrypoints=websecure"
      - "traefik.http.routers.rustdesk-web-client.tls=true"
      - "traefik.http.routers.rustdesk-web-client.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
```
4. Expose your `21118` and `21119` ports using Traefik, without
```yaml
  #####
  # Signal Server
  #
  # doc: hbbs listens on 21115 (TCP), 21116 (TCP/UDP) and 21118 (TCP),
  #####
  hbbs:
    container_name: rustdesk-signal-server
    image: rustdesk/rustdesk-server:1.1.9
    restart: unless-stopped
    command: "hbbs -r yourdomain.com -k _"
    ports:
      - "21115:21115/tcp"
      - "21116:21116/tcp"
      - "21116:21116/udp"
    labels:
      - traefik.enable=true
      # TCP : Web clients
      - traefik.tcp.routers.rustdesk-signal-server.entrypoints=rd-tcp-21118
      - traefik.tcp.routers.rustdesk-signal-server.rule=HostSNI(`*`)
      - traefik.tcp.routers.rustdesk-signal-server.service=rustdesk-signal-server
      - traefik.tcp.services.rustdesk-signal-server.loadbalancer.server.port=21118
      - traefik.tcp.routers.rustdesk-signal-server.tls=true
      - traefik.tcp.routers.rustdesk-signal-server.tls.passthrough=false
    volumes:
      - ./data/id_ed25519:/root/id_ed25519
      - ./data/id_ed25519.pub:/root/id_ed25519.pub
    depends_on:
      - hbbr

  #####
  # Relay Server
  #
  # doc: hbbr listens on 21117 (TCP) and 21119 (TCP)
  #####
  hbbr:
    container_name: rustdesk-relay-server
    image: rustdesk/rustdesk-server:1.1.9
    restart: unless-stopped
    command: "hbbr -k _"
    ports:
      - "21117:21117/tcp"
    labels:
      - traefik.enable=true
      # TCP : Web clients
      - traefik.tcp.routers.rustdesk-relay-server.entrypoints=rd-tcp-21119
      - traefik.tcp.routers.rustdesk-relay-server.rule=HostSNI(`*`)
      - traefik.tcp.routers.rustdesk-relay-server.service=rustdesk-relay-server
      - traefik.tcp.services.rustdesk-relay-server.loadbalancer.server.port=21119
      - traefik.tcp.routers.rustdesk-relay-server.tls=true
      - traefik.tcp.routers.rustdesk-relay-server.tls.passthrough=false
    volumes:
      - ./data/id_ed25519:/root/id_ed25519
      - ./data/id_ed25519.pub:/root/id_ed25519.pub
```

Notes
- You need to create entrypoints `rd-tcp-21118`.`rd-tcp-21119` and expose ports in Traefik config
- I only exposed `21118` and `21119` like that because in my experience, if all ports are configured with Traefik, there are disconnection/reconnection issues inside RustDesk Web Client, so I left them exposed with basic docker `ports` instructions (will retry though)
- Using `.tls.passthrough=false`, we use Traefik to do `wss <-> ws`, which allows us to have a secure `HTTPS` Web Client and an insecure `ws` Server, without issues (browser complaining about mixed content or anything)
