### DISCUSSION TITLE
Internet down, but no inter-LAN connection available

### DISCUSSION THREAD

**Discussion by truthsword** [rustdesk/rustdesk#6090] [Q&A]
I temporarily lost WAN due to ISP maintenance. During that time, I could not RDP between PCs, even though I was using the local LAN IP. What am I missing? Here's my docker compose
```
services:
  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r 192.168.1.11:21117
    volumes:
      - ./data:/root
    networks:
      - rustdeskz
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    networks:
      - rustdeskz
    restart: unless-stopped
```
Thanks!
