### DISCUSSION TITLE
Sign rustdesk files suddenly skipped

### DISCUSSION THREAD

**Discussion by chris-notley** [rustdesk/rustdesk#6549] [Q&A]
I forked the main branch a while ago and have been successfully running the build-nightly job for a while. 

I had configured a code signing certificate via the WINDOWS_PFX_BASE64/PASSWORD/SHA1_THUMPRINT secrets and it’s been happily signing the Windows 64 bit version for a few months. 

By chance I downloaded the latest nightly build earlier today and noticed the file was not signed. Looking in the actions log I see the “Sign Russell files” stage was skipped. 

Looking through the logs it was happily signing up until around a week ago when I synched with the upstream fork. 

As a test I did a new form of the main repo and set the secrets, running the nightly build manually and that too slipped the digital signature step.

I’ve been unable to see any obvious cause of the problem. Has anyone else seen a similar problem?

Thanks in advance for any tips!

![IMG_1450](https://github.com/rustdesk/rustdesk/assets/55881642/378c14f0-d15a-4f88-9171-e8ece2842559)
![IMG_1451](https://github.com/rustdesk/rustdesk/assets/55881642/2ef5e68a-2461-4d60-8891-3cffca5fc1c0)

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/6467

**Comment by deep-soft** [comment]
For those with the forks:
to sign Windows version with you're own certificate you need:
1. define you're own secrets:
   WINDOWS_PFX_BASE64
   PASSWORD
   SHA1_THUMPRINT
2. modify flutter_build.yml:
change line after uses: GermanBluefox/code-sign-action@v7
```
      - name: Sign rustdesk files
        uses: GermanBluefox/code-sign-action@v7
        if: false # env.UPLOAD_ARTIFACT == 'true'
        with:
```
to:
```
      - name: Sign rustdesk files
        uses: GermanBluefox/code-sign-action@v7
        # if: false # env.UPLOAD_ARTIFACT == 'true'
        with:
```

**Reply by chris-notley** [reply]
Thanks very much for this, I had to also modify the following section so the installer got signed too:

From:

```
      - name: Sign rustdesk self-extracted file
        uses: GermanBluefox/code-sign-action@v7
        if: false #env.UPLOAD_ARTIFACT == 'true'
        with:
```

To:

```
      - name: Sign rustdesk self-extracted file
        uses: GermanBluefox/code-sign-action@v7
        # if: false #env.UPLOAD_ARTIFACT == 'true'
        with:
```

But I wouldn't have known this without your pointer, thanks!
