### DISCUSSION TITLE
21114 is not up

### DISCUSSION THREAD

**Discussion by gpahlevanzadeh** [rustdesk/rustdesk#6902] [General]
I install hbbs and hbbr with 2 way : 1. deb files and 2. with npm and pm2 start hbbs and pm2start hbbr
How can I use we interface? which port can help me to access http?

**Comment by gpahlevanzadeh** [comment]
by the way I use OSS‌ version. Can I use web ?

**Reply by xlionjuan** [reply]
Only these ports is required
* 21115/tcp //TCP holepunching ~~Though it almost fail~~
* 21116/tcp, udp //ID
* 21117/tcp //Relay

**Reply by xlionjuan** [reply]
They need lots of work on WebRTC because WebClient needs it.

**Comment by grahamIT** [comment]
On my setup I have this docker compose file that forwards the ports. See below:

```
version: '3'

services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    volumes:
      - ./data:/root
    ports:
      - "21115:21115"
      - "21116:21116"
      - "21116:21116/udp"
#      - "21118:21118"
    depends_on:
      - hbbr
    restart: unless-stopped


  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    ports:
      - "21117:21117"
   #   - "21119:21119"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

```

You should be able to copy the ports
