### DISCUSSION TITLE
self hosting

### DISCUSSION THREAD

**Discussion by jasoncd** [rustdesk/rustdesk#7080] [Q&A]
I installed self hosting servers, hbbs hbbr using 'Set up your own server instance manually' by downloading the .deb file and running 'apt install ...deb'. I could not run './hbbs -r <relay-server-ip[:port]>' as error message says the port is already in use. When checking by 'ps aux| grep hbbr/s' found they are already running. They run on a single Linux machine (Ubuntu 20.04). Tested clients on the same LAN as the server machine with their 'ID Server' set to the LAN IP (e.g. 192.168..), connections OK. Tested clients with their 'ID Server' set to an IP tunnel address (the tunnel was provided by 'localtonet.com', e.g. 130.51..), while the two client machines are still on the same LAN network of the server machine, connections still OK - client machine A and B can log into each other. But if one of the client machines is moved outside the building to a different LAN network, say A, then A cannot connect to B, and B not able to connect to A either. What went wrong?  The message is "cannot connect via a relay server, please try later", etc. and never connect.

**Comment by grahamIT** [comment]
Install docker compose, add yourself to the docker group and then deploy this:
```
version: '3'

services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    restart: always
    volumes:
      - ./data:/root
    ports:
      - "21115:21115"
      - "21116:21116"
      - "21116:21116/udp"
    depends_on:
      - hbbr


  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    restart: always
    volumes:
      - ./data:/root
    ports:
      - "21117:21117"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

```

**Reply by xlionjuan** [reply]
Port ``21119`` and ``21118`` isn't required, because their web client isn't usable.

**Reply by heisenberg2980** [reply]
Does anyone know why the docker-compose.yml example provided in the instructions (https://rustdesk.com/docs/en/self-host/rustdesk-server-oss/docker/#docker-compose-examples) doesn´t include any port?

```
version: '3'

services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    volumes:
      - ./data:/root
    network_mode: "host"

    depends_on:
      - hbbr
    restart: unless-stopped


  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    network_mode: "host"
    restart: unless-stopped
```

**Reply by xlionjuan** [reply]
Because it is using `host` mode

**Reply by heisenberg2980** [reply]
@xlionjuan could you please expand on that? my docker-compose skills are a little rusty, how can you access the required ports if the container is not exposing them?

**Reply by xlionjuan** [reply]
`Host` mean expose ALL port and don't go though `docker bridge`

Just try it, you will notice it works

**Reply by grahamIT** [reply]
Actual saying that it exposes all ports is not a great way of putting it. You are sharing the network with the host and it is equivalent to running a program as root from a purely networking perspective.

**Reply by xlionjuan** [reply]
> Actual saying that it exposes all ports is not a great way of putting it. You are sharing the network with the host and it is equivalent to running a program as root from a purely networking perspective. 

You should has a firewall in front of the system, so it shouldn't a problem.

**Reply by grahamIT** [reply]
A Firewall does not mean anything for localhost. I would be more concerned about it attacking other localhost programswhich could lead to a container escape. It is best practice to explicitly expose ports in the docker compose as then the container is not sharing the hosts network.

**Reply by xlionjuan** [reply]
Just make sure you update your system and docker frequently

**Reply by gwijsman** [reply]
Thanks Graham, 
I like your docker compose (also with the watchtower!)
I removed the lines for ports 21118 and 21119 (no web)
you have a small typo (I think):
in the hbbs service you have two restart commands, maybe edit the "restart: always" out?

**Comment by xlionjuan** [comment]
For, Ubuntu, I recommend to use Docker, and you could use ``snap`` to install docker very easily.
````bash
sudo snap install docker
````

**Comment by xlionjuan** [comment]
Better version
Please replace  ``rustdesk.example.com`` to the domain that point to your server, and replace ``{your username}`` to your username.
After it created, go to ``/home/{your username}/docker/rustdesk-server``, find ``id_ed25519.pub``, this is needed for client to connect to the server.

Port forwarding settings:
``21115`` TCP
``21116`` Both TCP and UDP
``21117`` TCP

````yaml
version: '3'

services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r rustdesk.example.com:21117 -k _
    volumes:
      - /home/{your username}/docker/rustdesk-server:/root
    network_mode: host
    depends_on:
      - hbbr
    restart: always

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr -k _
    volumes:
      - /home/{your username}/docker/rustdesk-server:/root
    network_mode: host
    restart: always
 ````
