### DISCUSSION TITLE
Issue connecting to WAN

### DISCUSSION THREAD

**Discussion by Ironhydroxide** [rustdesk/rustdesk#9157] [General]
Hi All. 
I am new to RustDesk and a bit confused as to what's going on with my setup. 

Symptoms: 
can connect: WAN to LAN(with NotReady notification), LAN to LAN.
Cannot Connect: LAN to WAN, and WAN to WAN. (every WAN shows "Not Ready") 

My Setup:
Docker-Compose: 
```

services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    environment:
      - ALWAYS_USE_RELAY=Y
    command: hbbs -r <MYDomain>.com:21117
    volumes:
      - ./data:/root
    network_mode: host
    depends_on:
      - hbbr
    restart: unless-stopped
  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    network_mode: host
    restart: unless-stopped
networks: {}

```
Router Configured with local DNS resolving to the IP of the docker machine. 
Router Configured with Port Forwarding TCP/UDP range 21115-21119 to internal IP of docker machine
confirmed port forwarding on all ports with canyouseeme, and another for UDP (forget which , but showed open w/restriction)
Opened docker machine firewall on 21115-21119, both TCP/UDP. 

I have other services running under the domain on the same docker machine, which all route correctly to the server confirming my DDNS works as well. 

The Router is a Unifi Dream Machine, and can do WAY more than what I understand how to set it up, so maybe I have something done with security that's causing issues, I don't know there. 

I'm at a loss as to how I can connect from external just fine, but the discovery(?) doesn't work externally. 

Any suggestions/help would be appreciated.
