### DISCUSSION TITLE
Unable to connect via Relay server

### DISCUSSION THREAD

**Discussion by brhahlen** [rustdesk/rustdesk#9472] [General]
I am running Rustdesk in Docker and have Traefik setup as a reverse proxy.
On my LAN, I can connect to other pc's without a problem, hoewever, when I enable Relay, or try to connect from the outside, I am never able to connect.

The error I get, which seems relevant, is:
```
rustdesk  | [2024-09-26 06:58:22.113636 +00:00] DEBUG [src/rendezvous_server.rs:1101] WebSocket protocol error: httparse error: invalid token
rustdesk  |
rustdesk  | Caused by:
rustdesk  |     0: httparse error: invalid token
rustdesk  |     1: invalid token, hbbs::rendezvous_server:src/rendezvous_server.rs:1101:13
rustdesk  | [2024-09-26 06:58:22.120329 +00:00] DEBUG [src/rendezvous_server.rs:1097] Tcp connection from [::ffff:172.12.0.60]:50828, ws: true
rustdesk  | [2024-09-26 06:58:22.120423 +00:00] DEBUG [src/rendezvous_server.rs:1101] WebSocket protocol error: httparse error: invalid token
rustdesk  |
rustdesk  | Caused by:
rustdesk  |     0: httparse error: invalid token
rustdesk  |     1: invalid token, hbbs::rendezvous_server:src/rendezvous_server.rs:1101:13
```

My compose for the Rustdesk server looks like this:
```
  rustdesk:
    image: rustdesk/rustdesk-server-s6:latest
    container_name: rustdesk
    hostname: rustdesk
    env_file: rustdesk.env
    networks:
      - public_net
    volumes:
      - ${CONF_DIR}/rustdesk/db:/db
      - ${CONF_DIR}/rustdesk/data:/data
    labels:
      ## Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=public_net"
      # 21115/tcp
      - traefik.tcp.routers.rustdesk-rd5.entrypoints=rd5-tcp
      - traefik.tcp.routers.rustdesk-rd5.rule=HostSNI(`*`)
      - traefik.tcp.routers.rustdesk-rd5.service=rustdesk-rd5
      - traefik.tcp.services.rustdesk-rd5.loadbalancer.server.port=21115
      - traefik.tcp.routers.rustdesk-rd5.tls=false
      - traefik.tcp.routers.rustdesk-rd5.tls.passthrough=true
      # 21116/tcp
      - traefik.tcp.routers.rustdesk-rd6.entrypoints=rd6-tcp
      - traefik.tcp.routers.rustdesk-rd6.rule=HostSNI(`*`)
      - traefik.tcp.routers.rustdesk-rd6.service=rustdesk-rd6
      - traefik.tcp.services.rustdesk-rd6.loadbalancer.server.port=21116
      - traefik.tcp.routers.rustdesk-rd6.tls=false
      - traefik.tcp.routers.rustdesk-rd6.tls.passthrough=true
      # 21118/tcp
      - traefik.tcp.routers.rustdesk-rd8.entrypoints=rd8-tcp
      - traefik.tcp.routers.rustdesk-rd8.rule=HostSNI(`*`)
      - traefik.tcp.routers.rustdesk-rd8.service=rustdesk-rd8
      - traefik.tcp.services.rustdesk-rd8.loadbalancer.server.port=21118
      - traefik.tcp.routers.rustdesk-rd8.tls=false
      - traefik.tcp.routers.rustdesk-rd8.tls.passthrough=true
      # 21116/udp
      - traefik.udp.routers.rustdesk-rd6.entrypoints=rd6-udp
      - traefik.udp.routers.rustdesk-rd6.service=rustdesk-rd6
      - traefik.udp.services.rustdesk-rd6.loadbalancer.server.port=21116
      # 21117/tcp
      - traefik.tcp.routers.rustdesk-rd7.entrypoints=rd7-tcp
      - traefik.tcp.routers.rustdesk-rd7.rule=HostSNI(`*`)
      - traefik.tcp.routers.rustdesk-rd7.service=rustdesk-rd7
      - traefik.tcp.services.rustdesk-rd7.loadbalancer.server.port=21117
      - traefik.tcp.routers.rustdesk-rd7.tls=false
      - traefik.tcp.routers.rustdesk-rd7.tls.passthrough=true
      # 21119/tcp
      - traefik.tcp.routers.rustdesk-rd9.entrypoints=rd9-tcp
      - traefik.tcp.routers.rustdesk-rd9.rule=HostSNI(`*`)
      - traefik.tcp.routers.rustdesk-rd9.service=rustdesk-rd9
      - traefik.tcp.services.rustdesk-rd9.loadbalancer.server.port=21119
      - traefik.tcp.routers.rustdesk-rd9.tls=false
      - traefik.tcp.routers.rustdesk-rd9.tls.passthrough=true
```
The env-file is:
```
RELAY=rustdesk.${DOMAINNAME}:21117
ENCRYPTED_ONLY=1
DB_URL=/db/db_v2.sqlite3
# The private and public keys must be generated with the following command:
# Generate the private key: `openssl genpkey -algorithm Ed25519 -out private.key`
# Generate the public key: `openssl pkey -in private.key -pubout -out public.key`
# Display botk keys and copy them below: `cat private.key public.key`
# openssl rsa -in private.pem -pubout -out public.pem
KEY_PRIV=MYPRIVKEY
KEY_PUB=MYPUBKEY
RUST_LOG=debug
```
I have opened the ports on my USG and forwarded them.

In Traefik compose I have this as well:
```
  ports:
      - 21115:21115/tcp
      - 21116:21116/udp
      - 21116:21116/tcp
      - 21117:21117/tcp
      - 21118:21118/tcp
      - 21119:21119/tcp
```
What am I missing here?
