### DISCUSSION TITLE
Why self-hosted server always relayed?

### DISCUSSION THREAD

**Discussion by Lumysia** [rustdesk/rustdesk#9662] [Q&A]
Hi, can anyone help me pls?

- `Always relay = N` on every client, by default N on server?
- Clients directly connect to each other on the same LAN, but are always relayed through different networks(has public IPv6).

## Clients

- Windows 11
  - RustDesk: 1.3.1
  - IPv4
    - Mapping behavior: EndpointIndependent
    - Filtering behavior: AddressAndPortDependent
  - IPv6: Public
- Windows 11
  - RustDesk: 1.3.1
  - IPv4
    - Mapping behavior: EndpointIndependent
    - Filtering behavior: AddressAndPortDependent
  - IPv6: Public

> So I think they can establish direct connections with each other using IPv6?

## Server

- GreenCloud Tokyo Datacenter VPS.
- The domain `my.domain` has both A and AAAA records pointing to this VPS. DNS resolution via dig and nslookup confirms these records are working correctly. A website hosted on this VPS is accessible using both IPv4 and IPv6 addresses.
- No firewall rules.

### Version

- Linux 5.4.0-196-generic 216-Ubuntu SMP Thu Aug 29 13:26:53 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- Latest [rustdesk-server](https://hub.docker.com/r/rustdesk/rustdesk-server). I'm using watchtower to keep every container uptodate.

### docker

> docker compose config

```yml
services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: hbbs
    command: hbbs -r my.domain:21117
    environment:
      ENCRYPTED_ONLY: 1
    volumes:
      - ${DATA_PATH}/rustdesk:/root
    network_mode: host
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: hbbr
    command: hbbr
    volumes:
      - ${DATA_PATH}/rustdesk:/root
    network_mode: host
    restart: unless-stopped
```

> docker info

```
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 15
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-196-generic
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.828GiB
 Name: GreenCloud-JPTY-2-4G
 ID: ae8bed63-ee64-4cac-8f15-f6cf1706ba9a
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```
