### ISSUE TITLE
ERROR [libs/hbb_common/src/config.rs:538] Failed to store  config: Failed to create directory

### ISSUE THREAD

**Issue by truthsword** [rustdesk/rustdesk#11175]
### Bug Description

I see this error in logs
`ERROR [libs/hbb_common/src/config.rs:538] Failed to store  config: Failed to create directory`

This is a simple LAN-only system. IPs are used to interconnect devices.

### How to Reproduce

docker compose up -d

### Expected Behavior

No error

### Operating system(s) on local (controlling) side and remote (controlled) side

Debian 12 server with Win 11 clients

### RustDesk Version(s) on local (controlling) side and remote (controlled) side

1.38

### Screenshots

![](https://i.imgur.com/JtwkZaE.png)

### Additional Context

compose:
```
services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: hbbs
    restart: unless-stopped
    depends_on:
      - hbbr
    read_only: true
    security_opt:
      - no-new-privileges=true
    command: hbbs
    ports:
      - 21118:21118
    volumes:
      - data:/root

  hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: hbbr
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges=true
    command: hbbr
    volumes:
      - data:/root
```
