### ISSUE TITLE
Unable to connect to remote desktop through self-built relay server, prompt ID does not exist

### ISSUE THREAD

**Issue by dong50252409** [rustdesk/rustdesk#5658]
### Bug Description

I built a relay server in Debian according to https://rustdesk.com/docs/en/self-host/rustdesk-server-oss/docker/, but after the client is configured, it cannot connect to the remote desktop. The prompt ID does not exist. Where did I go wrong?

```
version: '3'

networks:
  rustdesk-net:
    external: false

services:
  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r xxx.xxx.com:21117
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    restart: unless-stopped
```

### How to Reproduce

If the intermediate server is configured, the prompt ID does not exist. After canceling these configurations, it can be connected normally, but the delay is very high.

### Expected Behavior

Get connected and see the screen of the remote.

### Operating system(s) on local side and remote side

Windows 10 -> Windows Server 2019

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.2.1

### Screenshots

![QQ图片20230911160413](https://github.com/rustdesk/rustdesk/assets/17381957/f904f83b-71f7-4bc6-a6b1-b80c81b4a07d)
![QQ图片20230911160456](https://github.com/rustdesk/rustdesk/assets/17381957/c5152627-c7b7-4dab-8b2b-b28136cb3f15)

### Additional Context
The telnet connection to port 21116 of the trunk server is normal

_No response_
