### ISSUE TITLE
Rustdesk flutter web fail loading 

### ISSUE THREAD

**Issue by eltorio** [rustdesk/rustdesk#7785]
### Bug Description

Today (20/04/2024) the latest CI build for web refuses to start 
```log
launch args: []
js_primitives.dart:42 _globalFFI init
js_primitives.dart:42 _globalFFI init end
js_primitives.dart:42 pullAb, force: ForcePullAb.listAndCurrent, quiet: false
codec.js:30 isSIMD: true
js_primitives.dart:42 UnimplementedError
js_primitives.dart:42 at Object.c (https://***.dev/main.dart.js:5465:19)
js_primitives.dart:42     at abn.afX (https://***.dev/main.dart.js:136262:15)
js_primitives.dart:42     at aej.D (https://***.dev/main.dart.js:128747:41)
js_primitives.dart:42     at Fw.cU (https://***.dev/main.dart.js:108887:32)
js_primitives.dart:42     at Fw.ne (https://***.dev/main.dart.js:108865:9)
js_primitives.dart:42     at Fw.Np (https://***.dev/main.dart.js:108814:10)
js_primitives.dart:42     at Fw.r7 (https://***.dev/main.dart.js:108815:18)
js_primitives.dart:42     at Fw.Ro (https://***.dev/main.dart.js:108863:11)
js_primitives.dart:42     at Fw.hS (https://***.dev/main.dart.js:108862:6)
js_primitives.dart:42     at Qh.EJ (https://***.dev/main.dart.js:108727:3)
common.ts:10 zstd ready
globals.js:476 init done
```

My CI runs each week and latest -Success 7:50PM April 13, 2024- was OK

### How to Reproduce

Build with:
```python
def build_web_app():
    os.chdir('flutter')
    os.chdir('web/js')
    system2('npx vite build')
    os.chdir('../..')
    system2('flutter pub upgrade')
    system2('flutter build web --release --source-maps')
    os.chdir("..")
```
my full CI yaml is
```yaml
 build-rustdesk-web:
    name: build-rustdesk-web
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        job:
          - { arch: x86_64, target: x86_64-unknown-linux-gnu, os: ubuntu-20.04 }
    env:
      RELEASE_NAME: web-basic
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Prepare env
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget npm

      - name: Install flutter
        uses: subosito/flutter-action@v2.12.0 #https://github.com/subosito/flutter-action/issues/277
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      # https://rustdesk.com/docs/en/dev/build/web/
      - name: Build web
        shell: bash
        run: |
          pushd flutter/web/js
          npm install yarn -g
          npm install typescript -g
          npm install protoc -g
          # Install protoc first, see: https://google.github.io/proto-lens/installing-protoc.html
          npm install ts-proto
          # Only works with vite <= 2.8, see: https://github.com/vitejs/vite/blob/main/docs/guide/build.md#chunking-strategy
          npm install vite@2.8
          yarn install && yarn build
          popd

          pushd flutter/web
          wget https://github.com/rustdesk/doc.rustdesk.com/releases/download/console/web_deps.tar.gz
          tar xzf web_deps.tar.gz
          popd

          python3 ./build.py --web
          pushd flutter
          # flutter build web --release
          cd build
          cp ../web/README.md web
          # TODO: Remove the following line when the web is almost complete.
          echo -e "\n\nThis build is for preview and not full functionality." >> web/README.md
          dir_name="${{ env.APP_NAME_LOW }}-${{ env.VERSION }}-${{ env.RELEASE_NAME }}"
          mv web/index.html web/rustdesk.html
          mv web/client.html web/index.html
          mv web "${dir_name}" && tar czf "${dir_name}".tar.gz "${dir_name}"
          cd "${dir_name}"
          zip -9 -r "../${dir_name}".zip .
          cd ..
          sha256sum "${dir_name}".tar.gz
          popd

      - name: Download, install mc and copy web files to S3
        run: |
          ls flutter/build/
          curl -o mc https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          ./mc alias set s3release https://${{ secrets.AWS_S3_ENDPOINT }} "${{ secrets.AWS_ACCESS_KEY_ID }}" "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "Copying flutter/build/${{ env.APP_NAME_LOW }}-${{ env.VERSION }}-${{ env.RELEASE_NAME }}.tar.gz to s3"
          echo "./mc cp 'flutter/build/${{ env.APP_NAME_LOW }}-${{ env.VERSION }}-${{ env.RELEASE_NAME }}.tar.gz' 's3release/${{ secrets.AWS_S3_BUCKET }}/${{ env.APP_NAME_LOW }}-releases/${{ env.APP_NAME_LOW }}-web-${{ env.VERSION }}.tar.gz'"
          ./mc cp 'flutter/build/${{ env.APP_NAME_LOW }}-${{ env.VERSION }}-${{ env.RELEASE_NAME }}.tar.gz' 's3release/${{ secrets.AWS_S3_BUCKET }}/${{ env.APP_NAME_LOW }}-releases/${{ env.APP_NAME_LOW }}-${{ env.VERSION }}-${{ env.RELEASE_NAME }}.tar.gz'
          ./mc cp 'flutter/build/${{ env.APP_NAME_LOW }}-${{ env.VERSION }}-${{ env.RELEASE_NAME }}.zip' 's3release/${{ secrets.AWS_S3_BUCKET }}/${{ env.APP_NAME_LOW }}-releases/${{ env.APP_NAME_LOW }}-${{ env.VERSION }}-${{ env.RELEASE_NAME }}.zip'

      - name: Publish to Cloudflare Pages
        uses: sctg-development/pages-action-without-url@main
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: flutter/build/${{ env.APP_NAME_LOW }}-${{ env.VERSION }}-${{ env.RELEASE_NAME }} # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
```

### Expected Behavior

As 1 week before the full rustdesk web should load

### Operating system(s) on local side and remote side

Microsoft Edge / Apple Safari

### RustDesk Version(s) on local side and remote side

git head

### Screenshots

none
