### ISSUE TITLE
1 computer out of 4 not connecting, giving "os error 10054" sometimes, sometimes connecting saying "waiting for image".

### ISSUE THREAD

**Issue by lightmaster** [rustdesk/rustdesk#7880]
### Bug Description

I have 4 computers. Computer A is a work computer with no admin access. Computer B is located at my house on my home network. Computers C and D are both located on the same remote network. Rustdesk self-hosted is running in docker on a different computer on the same network as Computer B, with ports 21115-21119 TCP/UDP forwarded to it.

Computers B, C, and D can all connect to each other without issue.
Computer A reports at the bottom "Not ready. Please check your connection." If I ignore that and try to connect to B, C, or D, it will ask for the password and the remote computer will pop up the window saying that a remote computer is attempting to connect with an accept button at the bottom. If I either type the password or click accept on the remote computer, "Logging in..." will eventually turn into "An existing connection was forcibly closed by the remote host. (os error 10054)". If I then hit "Reconnect", it will says "Connected, waiting for image..." but nothing will show up and it will eventually go back to the "os error 10054" again. The remote computer will say that a connection is established and minimize the connection window.

I have used Powershell's `Test-NetConnection` to verify that Computer A can connected to the Rustdesk computer using TCP on ports 21115-21119. I have also used a script I found at https://cloudbrothers.info/en/test-udp-connection-powershell/ to verify that Computer A can also make a UDP connection on port 21116. I don't think it's a port being blocked issue because of this.

I have also tried using "/r" after the ID and checking "Always connect via relay" with no success as was suggested in #1113.

### How to Reproduce

1. Install Rust Desktop via Docker
2. Attempt to connect from home computer, it works
3. Attempt to connect from work computer, gives error.
4. Test TCP and UDP connections from work and they connect fine.

### Expected Behavior

.... it should connect between the 2 computers?

### Operating system(s) on local side and remote side

Windows 11 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.3-2 -> 1.2.3-2

### Screenshots

![image](https://github.com/rustdesk/rustdesk/assets/5307827/16d24eff-a009-4434-a325-4861800341c5)
![image](https://github.com/rustdesk/rustdesk/assets/5307827/f470a325-417a-4402-adbc-d334959e8713)

### Additional Context

Rustdesk self hosted server is being ran in Docker v25.0.4 inside a Debian 12 VM

docker-compose.yml
```yaml
version: '3.9'

networks:
  rustdesk-net:
    external: false

services:
  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: rustdesk/rustdesk-server
    command: hbbs -r rustdesk.example.com:21117
    volumes:
      - /opt/docker/rustdesk/hbbs:/root:rw
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: on-failure:5

  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    image: rustdesk/rustdesk-server
    command: hbbr
    volumes:
      - /opt/docker/rustdesk/hbbr:/root:rw
    networks:
      - rustdesk-net
    restart: on-failure:5
```
