### ISSUE TITLE
Key Mismatch and official document seems wrong(or outdated)

### ISSUE THREAD

**Issue by JobberRT** [rustdesk/rustdesk#8271]
## Problem
I was running a self-hosted rustdesk docker instance for almost 2 years without filling the `Key` in network setting. And it gave me the best expirence abount remote control stuff. Yesterday I just upgrade the docker container to use the latset version of rustdesk server. And the issue came out: Connect to the server works, but connect to other client gives `Key Mismatch` error.

## What I have done
1. Restart the docker container, delete the presistent volumn to recreate a flesh new one
2. Reinstall the client software and OS
3. Search the issues and found these(no help): #8255 #6522 #3071 #1207 
4. Search the official document to make sure my memory about `Key` is correct(see screenshot below)

[Screenshot From Official Document Key Section](https://rustdesk.com/docs/en/self-host/rustdesk-server-oss/install/)
<img width="890" alt="image" src="https://github.com/rustdesk/rustdesk/assets/17498767/c6c745a0-3287-49a1-bbdb-9476d71869f7">

## What I have found as a workaround
I just copied the key from docker logs and filled in the network setting, and everything works fine, But I got nearly 40 client which runs on PVE KVM machine, it's such a pain to login to PVE and use noVNC to filled the Key...
<img width="955" alt="image" src="https://github.com/rustdesk/rustdesk/assets/17498767/9bbc8f37-28f0-4686-8b38-2d5b9ead5dad">

## What I guess
This behavior is a new version feature and didn't update on the official document. Because the old version of rustdesk works fine with no Key filled.

### How to Reproduce

Use this docker compose file to reproduce:
```yaml
version: '3.8'

services:
  hbbs:
    container_name: "hbbs"
    image: "rustdesk/rustdesk-server:latest"
    command: "hbbs"
    volumes:
      - "hbbs:/root"
    depends_on:
      - "hbbr"
    ports:
      - "21115:21115/tcp"
      - "21116:21116/tcp"
      - "21116:21116/udp"
      - "21118:21118/tcp"
    restart: "unless-stopped"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "256M"

  hbbr:
    container_name: "hbbr"
    image: "rustdesk/rustdesk-server:latest"
    command: "hbbr"
    volumes:
      - "hbbr:/root"
    ports:
      - "21117:21117/tcp"
      - "21119:21119/tcp"
    restart: "unless-stopped"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "256M"
volumes:
  hbbs:
    external: true
  hbbr:
    external: true
```

### Expected Behavior

Connection between client should be the same as what document says(Key isn't required for client)

### Operating system(s) on local side and remote side

Android, Windows 10, macOS both cross tested

### RustDesk Version(s) on local side and remote side

Both Version 1.2.3 (39)

### Screenshots

<img width="1148" alt="image" src="https://github.com/rustdesk/rustdesk/assets/17498767/71ea96be-a500-4e68-8012-c02d450974e6">
<img width="869" alt="image" src="https://github.com/rustdesk/rustdesk/assets/17498767/1bf3e699-0387-4405-824c-752e619f82e8">
