### ISSUE TITLE
The client always tries to access a non-existent port on the server: 21114

### ISSUE THREAD

**Issue by itning** [rustdesk/rustdesk#9360]
### Bug Description

Deploy the server side using docker compose:
```yml
name: rustdesk
services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    volumes:
      - /home/dockerdata/rustdesk:/root
    network_mode: "host"
    depends_on:
      - hbbr
    restart: always

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - /home/dockerdata/rustdesk:/root
    network_mode: "host"
    restart: always
```
Client ID, Network is set as shown below:
![image](https://github.com/user-attachments/assets/8a551b87-6213-4dde-814a-bdb57a2a103d)
The client can connect to the server normally and the status is ready.
Opened the Wireshark tool and found a request to access port 21114.
![image](https://github.com/user-attachments/assets/a96f10c8-3111-4bde-aadf-8e94c47a24a1)
Search by port number, and PID is client.
![image](https://github.com/user-attachments/assets/efd13997-79fb-46c4-86be-3e93024d2df6)
I found that port 21114 is used to communicate with the web console in the pro version. But the non-professional version should not have this feature, so is it possible to turn off initiating 21114 requests?
https://rustdesk.com/docs/zh-cn/self-host/rustdesk-server-pro/console/

### How to Reproduce

1. Build your own server
2. Normal communication between client and server
3. Monitor through Wireshark that the client makes a tcp request to the server on port 21114.

### Expected Behavior

Do not initiate requests to port 21114.

### Operating system(s) on local side and remote side

Windows 11 23H2 -> Linux 5.14.0-427.31.1.el9_4.x86_64

### RustDesk Version(s) on local side and remote side

1.3.0 -> 1.3.0

### Screenshots

![image](https://github.com/user-attachments/assets/a96f10c8-3111-4bde-aadf-8e94c47a24a1)
